name: NPM Publish

on:
  push: 
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run format

      - id: check
        uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/@juliannemarik/telemetry-dictionary/package.json
          static-checking: localIsNew
      - name: "Manually Versioned"
        if: steps.check.outputs.changed == 'true'
        run: echo "The package has already been manually versioned"
      - name: "Automatically Versioned"
        if: steps.check.outputs.changed == 'false'
        run: npm version minor

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: "Package Published"
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "A ${{ steps.publish.outputs.type }} version of telemetry-dictionary was published: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"