name: NPM Publish

on:
  push: 
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run format
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type == 'none'
        run: |
          echo "package was not published - version was not changed"
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "A ${{ steps.publish.outputs.type }} version of telemetry-dictionary was published: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"