name: NPM Publish

on:
  push: 
    branches: [ master ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run format

  version:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - run: npm version minor

  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: "Package Published"
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "A ${{ steps.publish.outputs.type }} version of telemetry-dictionary was published: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"